In [58]:
import numpy as np
class FitnessLandscape:

    def __init__(self, N):
        self.N = N
        self.one_values = np.random.random(N)
        self.zero_values = np.random.random(N)

    def fitness(self, loc):
        fs = np.where(loc, self.one_values,
                           self.zero_values)
        print(fs)
        return fs.mean()
    def best_location(self):
        best = np.empty((5,1))
        for i in range(self.N):
            if self.zero_values[i] > self.one_values[i]:
                best[i] = 0
            if self.zero_values[i] < self.one_values[i]:
                best[i] = 1
        return best

In [60]:
ls = FitnessLandscape(N = 5)

ls.fitness((0,0,0,0,0))
best = ls.best_location()
print(best)
ls.fitness(best)

[0.10658922 0.58379007 0.73788777 0.46707498 0.13665392]
[[1.]
 [0.]
 [0.]
 [1.]
 [0.]]
[[0.42887417 0.14133589 0.70965154 0.47305341 0.01959557]
 [0.10658922 0.58379007 0.73788777 0.46707498 0.13665392]
 [0.10658922 0.58379007 0.73788777 0.46707498 0.13665392]
 [0.42887417 0.14133589 0.70965154 0.47305341 0.01959557]
 [0.10658922 0.58379007 0.73788777 0.46707498 0.13665392]]


0.38564036059914797

In [63]:
import itertools
def binseq(k):
    return ["".join(x) for x in itertools.product(01, repeat=k)]

In [64]:
binseq(5)

['00000',
 '00001',
 '00010',
 '00011',
 '00100',
 '00101',
 '00110',
 '00111',
 '01000',
 '01001',
 '01010',
 '01011',
 '01100',
 '01101',
 '01110',
 '01111',
 '10000',
 '10001',
 '10010',
 '10011',
 '10100',
 '10101',
 '10110',
 '10111',
 '11000',
 '11001',
 '11010',
 '11011',
 '11100',
 '11101',
 '11110',
 '11111']